apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
