apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: tomcat
          ports:
            - containerPort: 8080
